theme = "catppuccin_macchiato"

[editor]
true-color = true
color-modes = true
cursorline = true
cursorcolumn = true
end-of-line-diagnostics = "hint"
# Prioritize home row keys for the 'gw' picker
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
clipboard-provider = "termcode"
insert-final-newline = false
popup-border = "all"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "¬"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Inline diagnostics - looks nice, but the code jumps around a bit too much for my liking
# [editor.inline-diagnostics]
# cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.file-picker]
hidden = false

[keys.select]
x = "select_line_below"
X = "select_line_above"
ret = "goto_word"

[keys.normal]
x = "select_line_below"
X = "select_line_above"
ret = "goto_word"

# Move around windows
A-h = "jump_view_left"
A-l = "jump_view_right"
A-j = "jump_view_down"
A-k = "jump_view_up"
# Lazygit popup window
C-l = ":sh zellij run -c -f --width 90%% --height 90%% -x 5%% -y 5%% -- lazygit"
# C-g = ':sh /usr/bin/tmux popup -d "#{pane_current_path}" -xC -yC -w80%% -h80%% -E lazygit'
 
# Kakoune-like extend (not sure about this)
# E = "extend_next_word_end"
# W = "extend_next_word_start"
# B = "extend_prev_word_end"
# H = "extend_char_left"
# L = "extend_char_right"

# Single quote minor mode
[keys.normal."'"]
w = "move_next_sub_word_start"
b = "move_prev_sub_word_start"
e = "move_next_sub_word_end"
# Kinda ugly regex to hop around tailwind classes. Uses the 'tw-' prefix to find
# classes from anywhere, but this won't work for most tailwind projects. Can be
# made more general by removing the prefix and everything after
t = '@/[A-Za-z0-9-\[\]\*\:\=&_\(\)\/,@]*tw-[A-Za-z0-9-\[\]\*\:\=&_\(\)\/,@]+<ret>'

# <space><space> for git commands
[keys.normal.space.space]
# Nicely formatted single-line git blame
b = ":sh git blame -L %{cursor_line},+1 %{buffer_name} | awk '{print $1}' | xargs git log -1 --format='medium'"
# Show a github URL
u = ":sh gh browse -n %{buffer_name}:%{cursor_line}"
# Open the file in the git blame pager and go to the current line
B = ":sh zellij run -fc -- git blame --color-by-age --color-lines %{buffer_name} && zellij action write-chars %{cursor_line}g"

# Backslash minor mode for config stuff
[keys.normal."\\"]
c = ":config-open"
r = ":config-reload"
l = ":open ~/.config/helix/languages.toml"
t = ":open ~/.config/tmux/tmux.conf"
j = ":open ~/.config/zellij/config.kdl"
z = ":open ~/.zshrc"
b = ":open ~/.bashrc"

# Other themes I like
# everforst_dark
# github_dark_dimmed
# material_darker
# nightfox
# onedark
# snazzy
# sonokai
